---
dirs:
  print: /home/tamil/client/XXX/kohaclone/koha-tmpl/overdue
  template: /home/tamil/client/XXX/etc/overdue
cycles:
  - branch: '*'
    type: '*'
    from: 14
    to: 20
    title: Claim 1
    claims:
      - type: email
        template: email/claim1.tx
      - type: print
        template: print/claim1.tx
  - branch: '*'
    type: '*'
    from: 21
    to: 26
    title: Claim 2
    claims:
      - type: email
        template: email/claim2.tx
      - type: print
        template: print/claim2.tx
  - branch: '*'
    type: '*'
    from: 27
    to: 89
    title: Claim 3
    claims:
      - type: print
        template: print/claim3.tx
